version: '3.4'

services:
    api:
      container_name: agrconclude.backend
      image: olopatskyi/agrconcludeapi
      ports:
        - "8000:80"
      environment:
        - ASPNETCORE_URLS=http://+:80
        - DatabaseSettings:Host=db
        - DatabaseSettings:Database=agrconclude

      depends_on:
        - db
    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: "password"
      ports:
        - "5432:5432"
      volumes:
        - local_pgdata:/var/lib/postgresql/data
    
volumes:
  local_pgdata:
      